# Generated by Django 2.2.7 on 2020-02-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=15, verbose_name='Langue')),
                ('img', models.ImageField(default='static/img/default_image.jpg', upload_to='static/img')),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='state',
        ),
        migrations.AddField(
            model_name='activity',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activity',
            name='prestataire',
            field=models.CharField(default='prestataire name', max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img',
            field=models.ImageField(default='static/img/default_image.jpg', upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Language'),
        ),
    ]
