# Generated by Django 2.2.7 on 2020-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='lang',
            field=models.CharField(default='now', max_length=2, verbose_name='Langue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='activity',
            name='img',
            field=models.ImageField(upload_to='static/imgActivity'),
        ),
    ]
