# Generated by Django 2.2.6 on 2019-12-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='lang',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
