# Generated by Django 2.2.7 on 2020-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200207_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='site',
            field=models.CharField(default='https://pontsuspendu.ch/', max_length=200),
            preserve_default=False,
        ),
    ]
