# Generated by Django 2.2.7 on 2020-02-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200210_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='abreviation',
            field=models.CharField(default='fr', max_length=10, verbose_name='abreviation'),
            preserve_default=False,
        ),
    ]
