# Generated by Django 2.2.7 on 2020-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200206_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
