# Generated by Django 2.2.7 on 2020-02-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20200210_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='lang',
        ),
        migrations.AddField(
            model_name='activityitem',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Language'),
        ),
    ]
