# Generated by Django 2.2.7 on 2020-02-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20200210_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityitem',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='abreviation',
            field=models.CharField(default='fr', max_length=10, verbose_name='abreviation'),
        ),
    ]
