# Generated by Django 2.2.7 on 2020-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_activityitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='imgMouse',
            field=models.ImageField(default='static/img/default_image.jpg', upload_to='static/img'),
        ),
    ]
