# Generated by Django 2.2.7 on 2020-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_language_imgmouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityitem',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
