# Generated by Django 2.2.7 on 2020-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20200212_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
