# Generated by Django 2.2.7 on 2020-02-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20200212_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activityitem',
            name='order',
            field=models.FloatField(default=1),
        ),
    ]
