# Generated by Django 2.2.6 on 2019-12-07 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='static/imgPosition')),
            ],
        ),
        migrations.CreateModel(
            name='PositionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('lang', models.CharField(max_length=2)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.Position')),
            ],
        ),
    ]
