# Generated by Django 2.2.6 on 2019-12-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionitem',
            name='audio',
            field=models.FileField(default='static/audio/test4.mp3', upload_to='static/audio/'),
        ),
    ]
