# Generated by Django 2.2.7 on 2020-02-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='lang',
            field=models.CharField(default='fr', max_length=2, verbose_name='Langue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionitem',
            name='audio',
            field=models.FileField(default='static/audio/test4.mp3', upload_to='static/audio/'),
        ),
        migrations.AlterField(
            model_name='positionitem',
            name='lang',
            field=models.CharField(max_length=2, verbose_name='Langue'),
        ),
    ]
