# Generated by Django 2.2.7 on 2020-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20200210_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionitem',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
