# Generated by Django 2.2.7 on 2020-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_positionitem_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionitem',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
