# Generated by Django 2.2.7 on 2020-02-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20200207_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='img',
        ),
        migrations.AddField(
            model_name='positionitem',
            name='img',
            field=models.ImageField(default='', upload_to='static/imgPosition'),
            preserve_default=False,
        ),
    ]
