# Generated by Django 2.2.7 on 2020-02-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_auto_20200208_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionitem',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
