# Generated by Django 2.2.7 on 2020-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_auto_20200211_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionitem',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
