# Generated by Django 2.2.7 on 2020-02-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_auto_20200207_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='number',
        ),
        migrations.RemoveField(
            model_name='positionitem',
            name='number',
        ),
        migrations.AddField(
            model_name='position',
            name='lang',
            field=models.CharField(default='fr', max_length=2, verbose_name='Langue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='positionitem',
            name='lang',
            field=models.CharField(max_length=2, verbose_name='Langue'),
        ),
    ]
