# Generated by Django 2.2.7 on 2020-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_positionitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='state',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionitem',
            name='state',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
